cmdgpt: cmdgpt::Conversation Class Reference
cmdgpt::Conversation Class Reference
Manages conversation history and context.
#include <cmdgpt.h>
Public Member Functions
Conversation ()=default
Default constructor creates empty conversation.
void add_message (std::string_view role, std::string_view content)
Add a message to the conversation.
void clear ()
Clear all messages from the conversation.
const std::vector< Message > & get_messages () const
Get all messages in the conversation.
void save_to_file (const std::filesystem::path &path) const
Save conversation to a JSON file.
void load_from_file (const std::filesystem::path &path)
Load conversation from a JSON file.
std::string to_json () const
Get conversation as formatted JSON string.
size_t estimate_tokens () const
Estimate token count for the conversation.
Private Attributes
std::vector< Message > messages_
Ordered list of conversation messages.
Static Private Attributes
static constexpr size_t MAX_CONTEXT_LENGTH = 100000
Maximum context length (~25k tokens)
Detailed Description
Manages conversation history and context.
The Conversation class maintains a history of messages exchanged with the AI model, automatically managing context length to stay within token limits. It provides persistence through JSON serialization and file I/O.
Conversation conv;
conv.add_message("system", "You are a helpful assistant");
conv.add_message("user", "Hello!");
conv.save_to_file("conversation.json");
Definition at line 376 of file cmdgpt.h.
Constructor & Destructor Documentation
Conversation()
cmdgpt::Conversation::Conversation () default
Default constructor creates empty conversation.
Member Function Documentation
add_message()
void cmdgpt::Conversation::add_message (std::string_view role, std::string_view content)
Add a message to the conversation.
Conversation class implementation.
Automatically trims old messages if context length exceeds limits
Parameters
role Role of the message sender ("system", "user", "assistant")
content Text content of the message
Definition at line 476 of file cmdgpt.cpp.
References estimate_tokens(), MAX_CONTEXT_LENGTH, and messages_.
Referenced by cmdgpt::run_interactive_mode().
clear()
void cmdgpt::Conversation::clear ()
Clear all messages from the conversation.
Definition at line 489 of file cmdgpt.cpp.
References messages_.
Referenced by cmdgpt::run_interactive_mode().
estimate_tokens()
size_t cmdgpt::Conversation::estimate_tokens () const
Estimate token count for the conversation.
Uses rough heuristic of 1 token ≈ 4 characters
Returns
Estimated number of tokens in the conversation
Definition at line 545 of file cmdgpt.cpp.
References messages_.
Referenced by add_message().
get_messages()
const std::vector< Message > & cmdgpt::Conversation::get_messages () const inline
Get all messages in the conversation.
Returns
Const reference to the vector of messages
Definition at line 401 of file cmdgpt.h.
References messages_.
Referenced by cmdgpt::get_gpt_chat_response().
load_from_file()
void cmdgpt::Conversation::load_from_file (const std::filesystem::path & path)
Load conversation from a JSON file.
Parameters
path Filesystem path to load the conversation from
Exceptions
std::runtime_error if file cannot be opened or parsed
Definition at line 505 of file cmdgpt.cpp.
References messages_.
Referenced by cmdgpt::run_interactive_mode().
save_to_file()
void cmdgpt::Conversation::save_to_file (const std::filesystem::path & path) const
Save conversation to a JSON file.
Parameters
path Filesystem path to save the conversation
Exceptions
std::runtime_error if file cannot be opened for writing
Definition at line 494 of file cmdgpt.cpp.
References to_json().
Referenced by cmdgpt::run_interactive_mode().
to_json()
std::string cmdgpt::Conversation::to_json () const
Get conversation as formatted JSON string.
Returns
JSON representation of the conversation with proper formatting
Definition at line 532 of file cmdgpt.cpp.
References messages_.
Referenced by save_to_file().
Member Data Documentation
MAX_CONTEXT_LENGTH
size_t cmdgpt::Conversation::MAX_CONTEXT_LENGTH = 100000 static constexpr private
Maximum context length (~25k tokens)
Definition at line 439 of file cmdgpt.h.
Referenced by add_message().
messages_
std::vector<Message> cmdgpt::Conversation::messages_ private
Ordered list of conversation messages.
Definition at line 438 of file cmdgpt.h.
Referenced by add_message(), clear(), estimate_tokens(), get_messages(), load_from_file(), and to_json().
The documentation for this class was generated from the following files:
cmdgpt.h
cmdgpt.cpp