cmdgpt: cmdgpt::ConfigFile Class Reference
cmdgpt::ConfigFile Class Reference
Configuration file manager.
#include <cmdgpt.h>
Public Member Functions
ConfigFile ()=default
Default constructor.
bool load (const std::filesystem::path &path)
Load configuration from file.
void save (const std::filesystem::path &path) const
Save configuration to file.
void apply_to (Config &config) const
Apply loaded configuration to a Config object.
Static Public Member Functions
static std::filesystem::path get_default_path ()
Get the default configuration file path.
static bool exists ()
Check if default config file exists.
Private Attributes
std::map< std::string, std::string > values_
Key-value pairs from config file.
Detailed Description
Configuration file manager.
Handles loading and saving configuration from/to .cmdgptrc files. Supports simple key=value format with comment lines starting with #.
ConfigFile config;
if (config.load(ConfigFile::get_default_path())) {
    config.apply_to(my_config);
}
Example .cmdgptrc file:
# cmdgpt configuration
api_key=sk-...
model=gpt-4
system_prompt=You are a helpful assistant
log_level=INFO
Definition at line 464 of file cmdgpt.h.
Constructor & Destructor Documentation
ConfigFile()
cmdgpt::ConfigFile::ConfigFile () default
Default constructor.
Member Function Documentation
apply_to()
void cmdgpt::ConfigFile::apply_to (Config & config) const
Apply loaded configuration to a Config object.
Only sets values that exist in the configuration file
Parameters
config Config object to update with loaded values
Definition at line 612 of file cmdgpt.cpp.
References log_levels, cmdgpt::Config::set_api_key(), cmdgpt::Config::set_log_file(), cmdgpt::Config::set_log_level(), cmdgpt::Config::set_model(), cmdgpt::Config::set_system_prompt(), and values_.
Referenced by main().
exists()
bool cmdgpt::ConfigFile::exists () static
Check if default config file exists.
Returns
true if ~/.cmdgptrc exists, false otherwise
Definition at line 647 of file cmdgpt.cpp.
References get_default_path().
Referenced by main().
get_default_path()
fs::path cmdgpt::ConfigFile::get_default_path () static
Get the default configuration file path.
Returns
Path to ~/.cmdgptrc
Exceptions
std::runtime_error if HOME environment variable is not set
Definition at line 636 of file cmdgpt.cpp.
Referenced by exists(), and main().
load()
bool cmdgpt::ConfigFile::load (const std::filesystem::path & path)
Load configuration from file.
ConfigFile class implementation.
Parses key=value pairs, ignoring comments and empty lines
Parameters
path Path to configuration file
Returns
true if file was successfully loaded, false otherwise
Definition at line 559 of file cmdgpt.cpp.
References values_.
Referenced by main().
save()
void cmdgpt::ConfigFile::save (const std::filesystem::path & path) const
Save configuration to file.
Writes all key=value pairs with header comment
Parameters
path Path to save configuration file
Exceptions
std::runtime_error if file cannot be opened for writing
Definition at line 595 of file cmdgpt.cpp.
References values_, and cmdgpt::VERSION.
Member Data Documentation
values_
std::map<std::string, std::string> cmdgpt::ConfigFile::values_ private
Key-value pairs from config file.
Definition at line 515 of file cmdgpt.h.
Referenced by apply_to(), load(), and save().
The documentation for this class was generated from the following files:
cmdgpt.h
cmdgpt.cpp