cmdgpt: cmdgpt::Config Class Reference
cmdgpt::Config Class Reference
Configuration management class using modern C++ features.
#include <cmdgpt.h>
Public Member Functions
Config ()=default
~Config ()=default
Config (const Config &)=delete
Config & operator= (const Config &)=delete
Config (Config &&)=default
Config & operator= (Config &&)=default
void set_api_key (std::string_view key)
Set API key with validation.
void set_system_prompt (std::string_view prompt)
Set system prompt with validation.
void set_model (std::string_view model)
Set model name with validation.
void set_log_file (std::string_view file)
Set log file path with validation.
void set_log_level (spdlog::level::level_enum level)
Set logging level.
const std::string & api_key () const noexcept
Get configured API key.
const std::string & system_prompt () const noexcept
Get configured system prompt.
const std::string & model () const noexcept
Get configured model name.
const std::string & log_file () const noexcept
Get configured log file path.
spdlog::level::level_enum log_level () const noexcept
Get configured log level.
void load_from_environment ()
Load configuration from environment variables.
void validate () const
Validate all configuration values.
Private Attributes
std::string api_key_
std::string system_prompt_ {DEFAULT_SYSTEM_PROMPT}
std::string model_ {DEFAULT_MODEL}
std::string log_file_ {"logfile.txt"}
spdlog::level::level_enum log_level_ {DEFAULT_LOG_LEVEL}
Detailed Description
Configuration management class using modern C++ features.
Definition at line 224 of file cmdgpt.h.
Constructor & Destructor Documentation
Config() [1/3]
cmdgpt::Config::Config () default
Referenced by Config(), Config(), operator=(), and operator=().
~Config()
cmdgpt::Config::~Config () default
Config() [2/3]
cmdgpt::Config::Config (const Config &) delete
References Config().
Config() [3/3]
cmdgpt::Config::Config (Config &&) default
References Config().
Member Function Documentation
api_key()
const std::string & cmdgpt::Config::api_key () const inline noexcept
Get configured API key.
Returns
API key string
Definition at line 274 of file cmdgpt.h.
References api_key_.
Referenced by cmdgpt::get_gpt_chat_response(), cmdgpt::get_gpt_chat_response(), and main().
load_from_environment()
void cmdgpt::Config::load_from_environment ()
Load configuration from environment variables.
Reads from:
OPENAI_API_KEY
OPENAI_SYS_PROMPT
OPENAI_GPT_MODEL
CMDGPT_LOG_FILE
CMDGPT_LOG_LEVEL
Definition at line 230 of file cmdgpt.cpp.
References api_key_, log_file_, log_level_, log_levels, model_, and system_prompt_.
Referenced by main().
log_file()
const std::string & cmdgpt::Config::log_file () const inline noexcept
Get configured log file path.
Returns
Log file path string
Definition at line 301 of file cmdgpt.h.
References log_file_.
Referenced by main().
log_level()
spdlog::level::level_enum cmdgpt::Config::log_level () const inline noexcept
Get configured log level.
Returns
spdlog log level
Definition at line 310 of file cmdgpt.h.
References log_level_.
Referenced by main().
model()
const std::string & cmdgpt::Config::model () const inline noexcept
Get configured model name.
Returns
Model name string
Definition at line 292 of file cmdgpt.h.
References model_.
Referenced by cmdgpt::get_gpt_chat_response(), cmdgpt::get_gpt_chat_response(), operator=(), and set_model().
operator=() [1/2]
Config & cmdgpt::Config::operator= (Config &&) default
References Config(), and model().
operator=() [2/2]
Config & cmdgpt::Config::operator= (const Config &) delete
References Config().
set_api_key()
void cmdgpt::Config::set_api_key (std::string_view key)
Set API key with validation.
Config class implementation.
Parameters
key OpenAI API key
Exceptions
ValidationException if key is invalid
Definition at line 192 of file cmdgpt.cpp.
References api_key_, and cmdgpt::validate_api_key().
Referenced by cmdgpt::ConfigFile::apply_to(), and main().
set_log_file()
void cmdgpt::Config::set_log_file (std::string_view file)
Set log file path with validation.
Parameters
file Path to log file
Exceptions
ValidationException if path is invalid
Definition at line 216 of file cmdgpt.cpp.
References log_file_.
Referenced by cmdgpt::ConfigFile::apply_to(), and main().
set_log_level()
void cmdgpt::Config::set_log_level (spdlog::level::level_enum level)
Set logging level.
Parameters
level spdlog log level
Definition at line 225 of file cmdgpt.cpp.
References log_level_.
Referenced by cmdgpt::ConfigFile::apply_to(), and main().
set_model()
void cmdgpt::Config::set_model (std::string_view model)
Set model name with validation.
Parameters
model GPT model name (e.g., "gpt-4", "gpt-3.5-turbo")
Exceptions
ValidationException if model name is invalid
Definition at line 207 of file cmdgpt.cpp.
References cmdgpt::DEFAULT_MODEL, model(), and model_.
Referenced by cmdgpt::ConfigFile::apply_to(), and main().
set_system_prompt()
void cmdgpt::Config::set_system_prompt (std::string_view prompt)
Set system prompt with validation.
Parameters
prompt System prompt for context
Exceptions
ValidationException if prompt exceeds size limits
Definition at line 198 of file cmdgpt.cpp.
References cmdgpt::DEFAULT_SYSTEM_PROMPT, cmdgpt::MAX_PROMPT_LENGTH, and system_prompt_.
Referenced by cmdgpt::ConfigFile::apply_to(), and main().
system_prompt()
const std::string & cmdgpt::Config::system_prompt () const inline noexcept
Get configured system prompt.
Returns
System prompt string
Definition at line 283 of file cmdgpt.h.
References system_prompt_.
Referenced by cmdgpt::get_gpt_chat_response(), and cmdgpt::run_interactive_mode().
validate()
void cmdgpt::Config::validate () const
Validate all configuration values.
Exceptions
ValidationException if any configuration is invalid
Definition at line 273 of file cmdgpt.cpp.
References api_key_, log_file_, cmdgpt::MAX_PROMPT_LENGTH, model_, system_prompt_, and cmdgpt::validate_api_key().
Referenced by cmdgpt::get_gpt_chat_response(), and cmdgpt::get_gpt_chat_response().
Member Data Documentation
api_key_
std::string cmdgpt::Config::api_key_ private
Definition at line 334 of file cmdgpt.h.
Referenced by api_key(), load_from_environment(), set_api_key(), and validate().
log_file_
std::string cmdgpt::Config::log_file_ {"logfile.txt"} private
Definition at line 337 of file cmdgpt.h.
Referenced by load_from_environment(), log_file(), set_log_file(), and validate().
log_level_
spdlog::level::level_enum cmdgpt::Config::log_level_ {DEFAULT_LOG_LEVEL} private
Definition at line 338 of file cmdgpt.h.
Referenced by load_from_environment(), log_level(), and set_log_level().
model_
std::string cmdgpt::Config::model_ {DEFAULT_MODEL} private
Definition at line 336 of file cmdgpt.h.
Referenced by load_from_environment(), model(), set_model(), and validate().
system_prompt_
std::string cmdgpt::Config::system_prompt_ {DEFAULT_SYSTEM_PROMPT} private
Definition at line 335 of file cmdgpt.h.
Referenced by load_from_environment(), set_system_prompt(), system_prompt(), and validate().
The documentation for this class was generated from the following files:
cmdgpt.h
cmdgpt.cpp