cmdgpt: main.cpp File Reference
main.cpp File Reference
Main entry point for cmdgpt command-line tool.
#include "cmdgpt.h"
#include "spdlog/sinks/ansicolor_sink.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/spdlog.h"
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <sysexits.h>
Functions
int main (int argc, const char *const argv[])
Parses command-line arguments and environment variables.
Detailed Description
Main entry point for cmdgpt command-line tool.
Author
Joern Ihlenburg
Date
2023-2024
This file contains the main function and command-line argument parsing for the cmdgpt tool. It handles initialization, configuration loading, and routing to appropriate modes (interactive or single-shot).
Definition in file main.cpp.
Function Documentation
main()
int main (int argc, const char *const argv[])
Parses command-line arguments and environment variables.
Definition at line 50 of file main.cpp.
References cmdgpt::Config::api_key(), cmdgpt::ConfigFile::apply_to(), cmdgpt::ConfigFile::exists(), cmdgpt::format_output(), cmdgpt::ConfigFile::get_default_path(), cmdgpt::get_gpt_chat_response(), gLogger, cmdgpt::ConfigFile::load(), cmdgpt::Config::load_from_environment(), cmdgpt::Config::log_file(), cmdgpt::Config::log_level(), log_levels, cmdgpt::parse_output_format(), cmdgpt::PLAIN, cmdgpt::print_help(), cmdgpt::run_interactive_mode(), cmdgpt::Config::set_api_key(), cmdgpt::Config::set_log_file(), cmdgpt::Config::set_log_level(), cmdgpt::Config::set_model(), cmdgpt::Config::set_system_prompt(), and cmdgpt::VERSION.