cmdgpt: cmdgpt::CmdGptException Class Reference
cmdgpt::CmdGptException Class Reference
#include <cmdgpt.h>
Public Member Functions
CmdGptException (const std::string &message)
Detailed Description
Definition at line 167 of file cmdgpt.h.
Constructor & Destructor Documentation
CmdGptException()
cmdgpt::CmdGptException::CmdGptException (const std::string & message) inline explicit
Definition at line 170 of file cmdgpt.h.
Referenced by cmdgpt::ApiException::ApiException(), cmdgpt::ConfigurationException::ConfigurationException(), cmdgpt::NetworkException::NetworkException(), and cmdgpt::ValidationException::ValidationException().
The documentation for this class was generated from the following file:
cmdgpt.h