cmdgpt: cmdgpt Namespace Reference
cmdgpt Namespace Reference
Main namespace for cmdgpt functionality.
Classes
class ApiException
class CmdGptException
class Config
Configuration management class using modern C++ features.
class ConfigFile
Configuration file manager.
class ConfigurationException
class Conversation
Manages conversation history and context.
struct Message
Represents a single message in a conversation.
class NetworkException
class ValidationException
Typedefs
using StreamCallback = std::function<void(const std::string& chunk)>
Streaming response callback type.
Enumerations
enum class HttpStatus : int {
EMPTY_RESPONSE = -1 , OK = 200 , BAD_REQUEST = 400 , UNAUTHORIZED = 401 ,
FORBIDDEN = 403 , NOT_FOUND = 404 , INTERNAL_SERVER_ERROR = 500
}
HTTP status codes used by the API.
enum class OutputFormat { PLAIN , MARKDOWN , JSON , CODE }
Output format options for response formatting.
Functions
OutputFormat parse_output_format (std::string_view format)
Convert string to OutputFormat enum.
void validate_api_key (std::string_view api_key)
Validates and sanitizes API key input.
void validate_prompt (std::string_view prompt)
Validates input prompt length and content.
std::string redact_api_key (std::string_view api_key)
Returns a redacted version of API key for logging.
void print_help ()
Prints the help message to the console.
std::string get_gpt_chat_response (std::string_view prompt, std::string_view api_key="", std::string_view system_prompt="", std::string_view model="")
Sends a chat completion request to the OpenAI API (legacy interface)
std::string get_gpt_chat_response (std::string_view prompt, const Config &config)
Sends a chat completion request to the OpenAI API (modern interface)
std::string get_gpt_chat_response (const Conversation &conversation, const Config &config)
Sends a chat completion request with conversation history.
void get_gpt_chat_response_stream (std::string_view prompt, const Config &config, StreamCallback callback)
Sends a streaming chat completion request.
void get_gpt_chat_response_stream (const Conversation &conversation, const Config &config, StreamCallback callback)
Sends a streaming chat completion request with conversation history.
std::string format_output (const std::string &content, OutputFormat format)
Format output based on the specified format.
void run_interactive_mode (Config &config)
Run interactive REPL mode.
Variables
constexpr std::string_view VERSION = "v0.3"
Current version of cmdgpt.
Default Configuration Values
constexpr std::string_view DEFAULT_MODEL = "gpt-4"
Default GPT model.
constexpr std::string_view DEFAULT_SYSTEM_PROMPT
Default system prompt.
constexpr spdlog::level::level_enum DEFAULT_LOG_LEVEL
Default log level.
HTTP Headers
constexpr std::string_view AUTHORIZATION_HEADER
HTTP Authorization header.
constexpr std::string_view CONTENT_TYPE_HEADER
HTTP Content-Type header.
constexpr std::string_view APPLICATION_JSON = "application/json"
JSON content type.
OpenAI API JSON Keys
constexpr std::string_view SYSTEM_ROLE = "system"
System role identifier.
constexpr std::string_view USER_ROLE = "user"
User role identifier.
constexpr std::string_view MODEL_KEY = "model"
Model key in API request.
constexpr std::string_view MESSAGES_KEY = "messages"
Messages array key.
constexpr std::string_view ROLE_KEY = "role"
Role key in message.
constexpr std::string_view CONTENT_KEY = "content"
Content key in message.
constexpr std::string_view CHOICES_KEY = "choices"
Choices array in response.
constexpr std::string_view FINISH_REASON_KEY
Finish reason in response.
API Configuration
constexpr std::string_view API_URL
OpenAI chat completions endpoint.
constexpr std::string_view SERVER_URL = "https://api.openai.com"
OpenAI API server URL.
Security and Validation Limits
constexpr size_t MAX_PROMPT_LENGTH = 1024 * 1024
Maximum prompt length (1MB)
constexpr size_t MAX_RESPONSE_LENGTH = 10 * 1024 * 1024
Maximum response length (10MB)
constexpr size_t MAX_API_KEY_LENGTH = 256
Maximum API key length.
constexpr int CONNECTION_TIMEOUT_SECONDS = 30
Connection timeout in seconds.
constexpr int READ_TIMEOUT_SECONDS = 60
Read timeout in seconds.
Detailed Description
Main namespace for cmdgpt functionality.
Contains all classes, functions, and constants for the cmdgpt command-line tool. Organized into several logical components:
Configuration management (Config, ConfigFile)
Conversation handling (Message, Conversation)
API interaction (get_gpt_chat_response functions)
Output formatting (OutputFormat, format_output)
Error handling (exception hierarchy)
Typedef Documentation
StreamCallback
using cmdgpt::StreamCallback = std::function<void(const std::string& chunk)>
Streaming response callback type.
Function signature for callbacks that receive streaming response chunks. Called repeatedly as data arrives from the API.
Parameters
chunk Partial response text received from the API
Definition at line 526 of file cmdgpt.h.
Enumeration Type Documentation
HttpStatus
enum class cmdgpt::HttpStatus : int strong
HTTP status codes used by the API.
Enumerator
EMPTY_RESPONSE
No response received or empty response body.
OK
Request successful.
BAD_REQUEST
Bad request format or parameters.
UNAUTHORIZED
Invalid or missing API key.
FORBIDDEN
Access forbidden.
NOT_FOUND
Endpoint not found.
INTERNAL_SERVER_ERROR
Server error.
Definition at line 127 of file cmdgpt.h.
OutputFormat
enum class cmdgpt::OutputFormat strong
Output format options for response formatting.
Determines how the API response will be formatted before display
Enumerator
PLAIN
Plain text output (default)
MARKDOWN
Markdown formatted output with headers.
JSON
JSON structured output with metadata.
CODE
Extract and display only code blocks.
Definition at line 143 of file cmdgpt.h.
Function Documentation
format_output()
std::string cmdgpt::format_output (const std::string & content, OutputFormat format)
Format output based on the specified format.
Format output based on specified format.
Parameters
content The content to format
format The desired output format
Returns
Formatted string
Definition at line 754 of file cmdgpt.cpp.
References CODE, JSON, MARKDOWN, PLAIN, and VERSION.
Referenced by main().
get_gpt_chat_response() [1/3]
std::string cmdgpt::get_gpt_chat_response (const Conversation & conversation, const Config & config)
Sends a chat completion request with conversation history.
Send chat request with conversation history.
Parameters
conversation The conversation history
config Configuration object containing API settings
Returns
The API response text
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
ValidationException on invalid input data
Definition at line 655 of file cmdgpt.cpp.
References cmdgpt::Config::api_key(), API_URL, APPLICATION_JSON, AUTHORIZATION_HEADER, CHOICES_KEY, CONNECTION_TIMEOUT_SECONDS, CONTENT_KEY, CONTENT_TYPE_HEADER, EMPTY_RESPONSE, cmdgpt::Conversation::get_messages(), gLogger, MESSAGES_KEY, cmdgpt::Config::model(), MODEL_KEY, OK, READ_TIMEOUT_SECONDS, ROLE_KEY, SERVER_URL, and cmdgpt::Config::validate().
get_gpt_chat_response() [2/3]
std::string cmdgpt::get_gpt_chat_response (std::string_view prompt, const Config & config)
Sends a chat completion request to the OpenAI API (modern interface)
Modern config-based API function using RAII and smart pointers.
Parameters
prompt The user's input prompt
config Configuration object containing API settings
Returns
The API response text
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
ValidationException on invalid input data
Definition at line 458 of file cmdgpt.cpp.
References cmdgpt::Config::api_key(), get_gpt_chat_response(), cmdgpt::Config::model(), cmdgpt::Config::system_prompt(), cmdgpt::Config::validate(), and validate_prompt().
get_gpt_chat_response() [3/3]
std::string cmdgpt::get_gpt_chat_response (std::string_view prompt, std::string_view api_key = "", std::string_view system_prompt = "", std::string_view model = "")
Sends a chat completion request to the OpenAI API (legacy interface)
Sends a chat completion request to the OpenAI API.
Parameters
prompt The user's input prompt
api_key OpenAI API key (empty string uses environment variable)
system_prompt System prompt to set context (empty string uses default)
model The model to use (empty string uses default)
Returns
The API response text
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
ValidationException on invalid input data
Parameters
prompt The user's input prompt
api_key OpenAI API key (empty string uses environment variable)
system_prompt System prompt to set context (empty string uses default)
model The model to use (empty string uses default)
Returns
The API response text
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
Definition at line 308 of file cmdgpt.cpp.
References API_URL, APPLICATION_JSON, AUTHORIZATION_HEADER, BAD_REQUEST, CHOICES_KEY, CONNECTION_TIMEOUT_SECONDS, CONTENT_KEY, CONTENT_TYPE_HEADER, DEFAULT_MODEL, DEFAULT_SYSTEM_PROMPT, EMPTY_RESPONSE, FINISH_REASON_KEY, FORBIDDEN, gLogger, INTERNAL_SERVER_ERROR, MAX_PROMPT_LENGTH, MAX_RESPONSE_LENGTH, MESSAGES_KEY, MODEL_KEY, NOT_FOUND, OK, READ_TIMEOUT_SECONDS, redact_api_key(), ROLE_KEY, SERVER_URL, SYSTEM_ROLE, UNAUTHORIZED, USER_ROLE, validate_api_key(), and validate_prompt().
Referenced by get_gpt_chat_response(), main(), and run_interactive_mode().
get_gpt_chat_response_stream() [1/2]
void cmdgpt::get_gpt_chat_response_stream (const Conversation & conversation, const Config & config, StreamCallback callback)
Sends a streaming chat completion request with conversation history.
Parameters
conversation The conversation history
config Configuration object containing API settings
callback Function called for each response chunk
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
ValidationException on invalid input data
get_gpt_chat_response_stream() [2/2]
void cmdgpt::get_gpt_chat_response_stream (std::string_view prompt, const Config & config, StreamCallback callback)
Sends a streaming chat completion request.
Parameters
prompt The user's input prompt
config Configuration object containing API settings
callback Function called for each response chunk
Exceptions
ApiException on HTTP errors
NetworkException on network/connection errors
ConfigurationException on invalid configuration
ValidationException on invalid input data
parse_output_format()
OutputFormat cmdgpt::parse_output_format (std::string_view format)
Convert string to OutputFormat enum.
Parse output format from string.
Case-insensitive parsing of format strings. Supports abbreviations.
Parameters
format String representation of format ("plain", "json", "markdown"/"md", "code")
Returns
Corresponding OutputFormat enum value, defaults to PLAIN if unknown
auto fmt = parse_output_format("json");  // Returns OutputFormat::JSON
auto fmt2 = parse_output_format("md");   // Returns OutputFormat::MARKDOWN
Definition at line 174 of file cmdgpt.cpp.
References CODE, JSON, MARKDOWN, and PLAIN.
Referenced by main().
print_help()
void cmdgpt::print_help ()
Prints the help message to the console.
Definition at line 72 of file cmdgpt.cpp.
Referenced by main().
redact_api_key()
std::string cmdgpt::redact_api_key (std::string_view api_key)
Returns a redacted version of API key for logging.
Parameters
api_key The API key to redact
Returns
Safely redacted API key for logging
Definition at line 151 of file cmdgpt.cpp.
Referenced by get_gpt_chat_response().
run_interactive_mode()
void cmdgpt::run_interactive_mode (Config & config)
Run interactive REPL mode.
Parameters
config Configuration object
Definition at line 795 of file cmdgpt.cpp.
References cmdgpt::Conversation::add_message(), cmdgpt::Conversation::clear(), get_gpt_chat_response(), cmdgpt::Conversation::load_from_file(), cmdgpt::Conversation::save_to_file(), cmdgpt::Config::system_prompt(), SYSTEM_ROLE, USER_ROLE, and VERSION.
Referenced by main().
validate_api_key()
void cmdgpt::validate_api_key (std::string_view api_key)
Validates and sanitizes API key input.
Parameters
api_key The API key to validate
Exceptions
ValidationException if API key is invalid
Definition at line 109 of file cmdgpt.cpp.
References MAX_API_KEY_LENGTH.
Referenced by get_gpt_chat_response(), cmdgpt::Config::set_api_key(), and cmdgpt::Config::validate().
validate_prompt()
void cmdgpt::validate_prompt (std::string_view prompt)
Validates input prompt length and content.
Parameters
prompt The prompt to validate
Exceptions
ValidationException if prompt is invalid
Definition at line 134 of file cmdgpt.cpp.
References MAX_PROMPT_LENGTH.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
Variable Documentation
API_URL
std::string_view cmdgpt::API_URL inline constexpr
Initial value:
=
    "/v1/chat/completions"
OpenAI chat completions endpoint.
Definition at line 110 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
APPLICATION_JSON
std::string_view cmdgpt::APPLICATION_JSON = "application/json" inline constexpr
JSON content type.
Definition at line 92 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
AUTHORIZATION_HEADER
std::string_view cmdgpt::AUTHORIZATION_HEADER inline constexpr
Initial value:
=
    "Authorization"
HTTP Authorization header.
Definition at line 88 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
CHOICES_KEY
std::string_view cmdgpt::CHOICES_KEY = "choices" inline constexpr
Choices array in response.
Definition at line 103 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
CONNECTION_TIMEOUT_SECONDS
int cmdgpt::CONNECTION_TIMEOUT_SECONDS = 30 inline constexpr
Connection timeout in seconds.
Definition at line 120 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
CONTENT_KEY
std::string_view cmdgpt::CONTENT_KEY = "content" inline constexpr
Content key in message.
Definition at line 102 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
CONTENT_TYPE_HEADER
std::string_view cmdgpt::CONTENT_TYPE_HEADER inline constexpr
Initial value:
=
    "Content-Type"
HTTP Content-Type header.
Definition at line 90 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
DEFAULT_LOG_LEVEL
spdlog::level::level_enum cmdgpt::DEFAULT_LOG_LEVEL inline constexpr
Initial value:
=
    spdlog::level::warn
Default log level.
Definition at line 82 of file cmdgpt.h.
DEFAULT_MODEL
std::string_view cmdgpt::DEFAULT_MODEL = "gpt-4" inline constexpr
Default GPT model.
Definition at line 79 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and cmdgpt::Config::set_model().
DEFAULT_SYSTEM_PROMPT
std::string_view cmdgpt::DEFAULT_SYSTEM_PROMPT inline constexpr
Initial value:
=
    "You are a helpful assistant!"
Default system prompt.
Definition at line 80 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and cmdgpt::Config::set_system_prompt().
FINISH_REASON_KEY
std::string_view cmdgpt::FINISH_REASON_KEY inline constexpr
Initial value:
=
    "finish_reason"
Finish reason in response.
Definition at line 104 of file cmdgpt.h.
Referenced by get_gpt_chat_response().
MAX_API_KEY_LENGTH
size_t cmdgpt::MAX_API_KEY_LENGTH = 256 inline constexpr
Maximum API key length.
Definition at line 119 of file cmdgpt.h.
Referenced by validate_api_key().
MAX_PROMPT_LENGTH
size_t cmdgpt::MAX_PROMPT_LENGTH = 1024 * 1024 inline constexpr
Maximum prompt length (1MB)
Definition at line 117 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), cmdgpt::Config::set_system_prompt(), cmdgpt::Config::validate(), and validate_prompt().
MAX_RESPONSE_LENGTH
size_t cmdgpt::MAX_RESPONSE_LENGTH = 10 * 1024 * 1024 inline constexpr
Maximum response length (10MB)
Definition at line 118 of file cmdgpt.h.
Referenced by get_gpt_chat_response().
MESSAGES_KEY
std::string_view cmdgpt::MESSAGES_KEY = "messages" inline constexpr
Messages array key.
Definition at line 100 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
MODEL_KEY
std::string_view cmdgpt::MODEL_KEY = "model" inline constexpr
Model key in API request.
Definition at line 99 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
READ_TIMEOUT_SECONDS
int cmdgpt::READ_TIMEOUT_SECONDS = 60 inline constexpr
Read timeout in seconds.
Definition at line 121 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
ROLE_KEY
std::string_view cmdgpt::ROLE_KEY = "role" inline constexpr
Role key in message.
Definition at line 101 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
SERVER_URL
std::string_view cmdgpt::SERVER_URL = "https://api.openai.com" inline constexpr
OpenAI API server URL.
Definition at line 112 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and get_gpt_chat_response().
SYSTEM_ROLE
std::string_view cmdgpt::SYSTEM_ROLE = "system" inline constexpr
System role identifier.
Definition at line 97 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and run_interactive_mode().
USER_ROLE
std::string_view cmdgpt::USER_ROLE = "user" inline constexpr
User role identifier.
Definition at line 98 of file cmdgpt.h.
Referenced by get_gpt_chat_response(), and run_interactive_mode().
VERSION
std::string_view cmdgpt::VERSION = "v0.3" inline constexpr
Current version of cmdgpt.
Definition at line 75 of file cmdgpt.h.
Referenced by format_output(), main(), run_interactive_mode(), and cmdgpt::ConfigFile::save().